"""Not optional

Revision ID: 0c6b6a5b1217
Revises: 2c9393ffe781
Create Date: 2024-02-22 21:29:56.796840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6b6a5b1217'
down_revision = '2c9393ffe781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departamento', schema=None) as batch_op:
        batch_op.alter_column('is_ug',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departamento', schema=None) as batch_op:
        batch_op.alter_column('is_ug',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
