"""Subplanes absorption

Revision ID: 2dd62b721d9a
Revises: 04ca06c178cc
Create Date: 2024-03-13 01:44:43.382866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd62b721d9a'
down_revision = '04ca06c178cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subplan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absorb', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subplan', schema=None) as batch_op:
        batch_op.drop_column('absorb')

    # ### end Alembic commands ###
