"""Planes

Revision ID: 3119b7038342
Revises: 0c6b6a5b1217
Create Date: 2024-02-24 18:58:07.011122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3119b7038342'
down_revision = '0c6b6a5b1217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('plan_ramo',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('ramo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['ramo_id'], ['ramo.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'ramo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_ramo')
    op.drop_table('plan')
    # ### end Alembic commands ###
