"""Subplanes carreras

Revision ID: 5020524c435c
Revises: e6fe5bf69f14
Create Date: 2024-03-13 00:35:15.170070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5020524c435c'
down_revision = 'e6fe5bf69f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrera', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('carrera')

    # ### end Alembic commands ###
