"""SQLite to Postgres

Revision ID: 6e532b0308ae
Revises: 
Create Date: 2024-03-15 17:51:49.356462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e532b0308ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('codigo', sa.String(length=128), nullable=False),
    sa.Column('ucampus_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=6), nullable=True),
    sa.Column('is_ug', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('ucampus_id')
    )
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ucampus_id', sa.String(length=128), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ucampus_id')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('carrera', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ramo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=128), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('sct', sa.Integer(), nullable=False),
    sa.Column('sustentabilidad', sa.Boolean(), nullable=False),
    sa.Column('requisitos', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], name='fk_user_departamento'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('seccion', sa.Integer(), nullable=False),
    sa.Column('cupos', sa.Integer(), nullable=False),
    sa.Column('cupos_ocupados', sa.Integer(), nullable=False),
    sa.Column('ramo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ramo_id'], ['ramo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('año', 'semestre', 'seccion', 'ramo_id', name='sección')
    )
    op.create_table('subplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('absorb', sa.Boolean(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('parent_subplan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_subplan_id'], ['subplan.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso_profesor',
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('curso_id', 'profesor_id')
    )
    op.create_table('subplan_ramo',
    sa.Column('subplan_id', sa.Integer(), nullable=False),
    sa.Column('ramo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ramo_id'], ['ramo.id'], ),
    sa.ForeignKeyConstraint(['subplan_id'], ['subplan.id'], ),
    sa.PrimaryKeyConstraint('subplan_id', 'ramo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subplan_ramo')
    op.drop_table('curso_profesor')
    op.drop_table('subplan')
    op.drop_table('curso')
    op.drop_table('user')
    op.drop_table('ramo')
    op.drop_table('plan')
    op.drop_table('profesor')
    op.drop_table('departamento')
    # ### end Alembic commands ###
