"""Subplanes

Revision ID: 7f3bc323c615
Revises: 3119b7038342
Create Date: 2024-03-12 22:38:17.247918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3bc323c615'
down_revision = '3119b7038342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('parent_subplan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_subplan_id'], ['subplan.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subplan')
    # ### end Alembic commands ###
