"""Cupos

Revision ID: 8899ce91037b
Revises: b6e86360c666
Create Date: 2024-02-22 17:02:35.658492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8899ce91037b'
down_revision = 'b6e86360c666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cupos', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cupos_ocupados', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_column('cupos_ocupados')
        batch_op.drop_column('cupos')

    # ### end Alembic commands ###
