"""Sección unique constraint

Revision ID: b6e86360c666
Revises: 5b19e6432d5b
Create Date: 2024-02-22 16:06:00.897422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e86360c666'
down_revision = '5b19e6432d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.create_unique_constraint('sección', ['año', 'semestre', 'seccion', 'ramo_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_constraint('sección', type_='unique')

    # ### end Alembic commands ###
