"""Modernize

Revision ID: d652bfe262e5
Revises: 5be10283f47a
Create Date: 2024-02-21 18:31:26.324975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd652bfe262e5'
down_revision = '5be10283f47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor')
    op.drop_table('department')
    op.drop_table('course')
    op.drop_table('section')
    op.drop_table('user')
    op.drop_table('section_professor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_professor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('section_id', sa.INTEGER(), nullable=False),
    sa.Column('professor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('section',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('semester', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('section', sa.VARCHAR(length=128), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('code', sa.VARCHAR(length=128), nullable=False),
    sa.Column('department', sa.INTEGER(), nullable=False),
    sa.Column('sct', sa.INTEGER(), nullable=False),
    sa.Column('requisitos', sa.VARCHAR(length=128), nullable=False),
    sa.ForeignKeyConstraint(['department'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ucampus_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('code', sa.VARCHAR(length=128), nullable=False),
    sa.Column('color', sa.VARCHAR(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('ucampus_id')
    )
    op.create_table('professor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ucampus_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ucampus_id')
    )
    # ### end Alembic commands ###
