"""Modernize for real

Revision ID: dc250d3fe02e
Revises: d652bfe262e5
Create Date: 2024-02-21 18:33:41.710212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc250d3fe02e'
down_revision = 'd652bfe262e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('codigo', sa.String(length=128), nullable=False),
    sa.Column('ucampus_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('ucampus_id')
    )
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ucampus_id', sa.String(length=128), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ucampus_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ramo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=128), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('sct', sa.Integer(), nullable=False),
    sa.Column('sustentabilidad', sa.Boolean(), nullable=False),
    sa.Column('requisitos', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('seccion', sa.Integer(), nullable=False),
    sa.Column('ramo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ramo_id'], ['ramo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso_profesor',
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('curso_id', 'profesor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curso_profesor')
    op.drop_table('curso')
    op.drop_table('ramo')
    op.drop_table('users')
    op.drop_table('profesor')
    op.drop_table('departamento')
    # ### end Alembic commands ###
