"""Subplanes fix

Revision ID: fe2b4f968a6d
Revises: 7f3bc323c615
Create Date: 2024-03-12 22:53:46.081417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2b4f968a6d'
down_revision = '7f3bc323c615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_ramo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_ramo',
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.Column('ramo_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['ramo_id'], ['ramo.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'ramo_id')
    )
    # ### end Alembic commands ###
